import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Navigation
    "nav.home": "Início",
    "nav.services": "Serviços",
    "nav.private": "Privado",
    "nav.companies": "Empresas",
    "nav.investors": "Investidores",
    "nav.portfolio": "Portfolio",
    "nav.blog": "Blog",
    "nav.contact": "Contacto",
    "nav.quote": "Pedir Orçamento",
    "nav.login": "Entrar",
    "nav.openMenu": "Abrir menu",
    "nav.closeMenu": "Fechar menu",
    "nav.clientArea": "Área Cliente",
    "nav.logout": "Sair",
    "nav.theme": "Tema",
    "nav.language": "Idioma",
    
    // Hero Section
    "hero.tagline": "Arquitetura & Design",
    "hero.title": "Criamos espaços que",
    "hero.titleHighlight": "inspiram",
    "hero.description": "Desenhamos ecossistemas prontos para o futuro — para viver, trabalhar e aprender. Combinamos 20+ anos de experiência internacional com inovação digital e sustentabilidade.",
    "hero.cta": "Pedir Orçamento",
    "hero.viewPortfolio": "Ver Portfolio",
    "hero.experience": "Anos de experiência internacional em arquitetura",
    "hero.imageAlt": "Projeto de arquitetura ARIFA Studio",
    
    // About Section
    "about.subtitle": "Sobre Nós",
    "about.title": "Arquitetura com alma portuguesa,",
    "about.titleHighlight": "visão global",
    "about.description1": "A ARIFA Studio combina mais de 20 anos de experiência internacional em arquitetura, com projetos desenvolvidos em Portugal, Noruega, Suécia e Angola. Fundada em 2022, trazemos uma visão contemporânea focada na transformação digital do setor da construção.",
    "about.description2": "Especializamo-nos em BIM, design sustentável, eficiência energética e soluções inovadoras. Acreditamos na digitalização inteligente, na colaboração estratégica e em práticas éticas e sustentáveis para criar ativos de alto desempenho.",
    "about.quote": "Design é inteligência tornada visível",
    "about.stat1": "Anos de experiência",
    "about.stat2": "Países de atuação",
    "about.stat3": "Especialização digital",
    "about.stat4": "Fundação do estúdio",
    "about.explorePortfolio": "Explorar Portfolio",
    
    // CTA Section
    "cta.subtitle": "Comece hoje",
    "cta.title": "Pronto para dar vida ao seu projeto?",
    "cta.description": "Seja uma casa de sonho, um espaço corporativo inovador ou um investimento imobiliário estratégico — estamos aqui para transformar a sua visão em realidade.",
    "cta.freeConsultation": "Consulta gratuita",
    "cta.freeConsultationDesc": "Primeira reunião sem compromisso para conhecer o seu projeto",
    "cta.response24h": "Resposta em 24h",
    "cta.response24hDesc": "Garantimos uma resposta rápida a todos os pedidos",
    "cta.detailedQuote": "Orçamento detalhado",
    "cta.detailedQuoteDesc": "Proposta clara e transparente sem surpresas",
    "cta.requestQuote": "Solicitar Orçamento",
    "cta.imageAlt": "Reunião com equipa ARIFA Studio",
    
    // Segment Selector
    "segments.subtitle": "Como podemos ajudar",
    "segments.title": "Soluções adaptadas às suas necessidades",
    "segments.description": "Cada cliente é único. Por isso, oferecemos serviços especializados para diferentes perfis e objetivos.",
    "segments.learnMore": "Saber mais",
    "segments.private.title": "Clientes Privados",
    "segments.private.description": "Transformamos a sua visão numa casa de sonho. Desde moradias a apartamentos, criamos espaços que refletem a sua personalidade.",
    "segments.private.feature1": "Moradias unifamiliares",
    "segments.private.feature2": "Remodelações",
    "segments.private.feature3": "Design de interiores",
    "segments.companies.title": "Empresas",
    "segments.companies.description": "Espaços corporativos que potenciam produtividade e bem-estar. Soluções para escritórios, retalho e hospitalidade.",
    "segments.companies.feature1": "Escritórios",
    "segments.companies.feature2": "Espaços comerciais",
    "segments.companies.feature3": "Hotéis e restaurantes",
    "segments.investors.title": "Investidores",
    "segments.investors.description": "Maximizamos o retorno do seu investimento imobiliário. Estudos de viabilidade, projetos de promoção e reabilitação urbana.",
    "segments.investors.feature1": "Estudos de viabilidade",
    "segments.investors.feature2": "Promoção imobiliária",
    "segments.investors.feature3": "Reabilitação urbana",
    
    // Featured Projects
    "projects.subtitle": "Portfolio",
    "projects.title": "Projetos em destaque",
    "projects.viewAll": "Ver todos os projetos",
    
    // Testimonials
    "testimonials.subtitle": "Testemunhos",
    "testimonials.title": "O que dizem os nossos clientes",
    "testimonials.previous": "Anterior",
    "testimonials.next": "Próximo",
    "testimonials.goTo": "Ir para testemunho",
    
    // Footer
    "footer.tagline": "We design future-ready ecosystems for living, working and learning.",
    "footer.segments": "Segmentos",
    "footer.company": "Empresa",
    "footer.legal": "Legal",
    "footer.contact": "Contacto",
    "footer.newsletter": "Newsletter",
    "footer.newsletterDesc": "Receba novidades e dicas de arquitetura.",
    "footer.copyright": "Todos os direitos reservados.",
    "footer.aboutUs": "Sobre Nós",
    "footer.privacyPolicy": "Política de Privacidade",
    "footer.terms": "Termos e Condições",
    
    // Portfolio Page
    "portfolio.subtitle": "Portfolio",
    "portfolio.title": "Os nossos projetos",
    "portfolio.description": "Uma seleção dos nossos trabalhos mais recentes em arquitetura, design de interiores e promoção imobiliária.",
    "portfolio.searchPlaceholder": "Pesquisar projetos...",
    "portfolio.allSegments": "Todos os Segmentos",
    "portfolio.all": "Todos",
    "portfolio.allLocations": "Todas",
    "portfolio.noResults": "Nenhum projeto encontrado com os filtros selecionados.",
    "portfolio.noProjects": "Nenhum projeto encontrado.",
    "portfolio.clearFilters": "Limpar filtros",
    "portfolio.projectsFound": "projetos encontrados",
    "portfolio.projectFound": "projeto encontrado",
    "portfolio.cta.title": "Tem um projeto em mente?",
    "portfolio.cta.description": "Conte-nos sobre as suas ideias. Estamos prontos para transformar a sua visão em realidade.",
    "portfolio.cta.button": "Fale Connosco",
    
    // Private Page
    "private.subtitle": "Clientes Privados",
    "private.title": "A casa dos seus",
    "private.titleHighlight": "sonhos",
    "private.description": "Criamos espaços que contam a sua história. Cada projeto é único, desenvolvido à medida das suas necessidades, estilo de vida e aspirações.",
    "private.cta": "Marcar Consulta Gratuita",
    "private.services.subtitle": "Serviços",
    "private.services.title": "Soluções para o seu lar",
    "private.services.1.title": "Moradias Unifamiliares",
    "private.services.1.description": "Projetos de raiz personalizados que combinam funcionalidade, estética e sustentabilidade. Do conceito à entrega de chave na mão.",
    "private.services.2.title": "Design de Interiores",
    "private.services.2.description": "Espaços que refletem a sua personalidade. Seleção de materiais, mobiliário e iluminação para criar ambientes únicos.",
    "private.services.3.title": "Remodelações",
    "private.services.3.description": "Transformamos espaços existentes em casas modernas e funcionais, respeitando a identidade original do edifício.",
    "private.process.subtitle": "Processo",
    "private.process.title": "Como trabalhamos consigo",
    "private.process.1.title": "Consulta Inicial",
    "private.process.1.description": "Reunião para conhecer as suas necessidades, gostos e orçamento.",
    "private.process.2.title": "Estudo Preliminar",
    "private.process.2.description": "Apresentação de conceitos e soluções espaciais para aprovação.",
    "private.process.3.title": "Projeto de Execução",
    "private.process.3.description": "Desenvolvimento detalhado de todos os elementos técnicos.",
    "private.process.4.title": "Acompanhamento de Obra",
    "private.process.4.description": "Supervisão da construção para garantir qualidade e conformidade.",
    "private.cta2.title": "Pronto para começar?",
    "private.cta2.description": "A primeira consulta é gratuita e sem compromisso. Conte-nos sobre o seu projeto e vamos transformá-lo em realidade.",
    "private.cta2.button": "Agendar Consulta",
    
    // Companies Page
    "companies.subtitle": "Empresas",
    "companies.title": "Espaços que",
    "companies.titleHighlight": "transformam",
    "companies.titleEnd": "negócios",
    "companies.description": "O ambiente de trabalho influencia diretamente a performance da sua equipa. Criamos espaços corporativos que inspiram, motivam e retêm talento.",
    "companies.cta": "Solicitar Proposta",
    "companies.services.subtitle": "Áreas de Atuação",
    "companies.services.title": "Soluções para empresas",
    "companies.services.1.title": "Escritórios & Espaços de Trabalho",
    "companies.services.1.description": "Design centrado nas pessoas com integração BIM. Espaços que potenciam produtividade, bem-estar e retenção de talento.",
    "companies.services.2.title": "Instalações Educativas & Saúde",
    "companies.services.2.description": "Escolas, centros de formação e instalações de saúde projetadas para alto desempenho e conforto dos utilizadores.",
    "companies.services.3.title": "Residências Seniores & Hospitalidade",
    "companies.services.3.description": "Espaços de vida assistida e hospitalidade com foco em acessibilidade, sustentabilidade e experiência do utilizador.",
    "companies.benefits.subtitle": "Benefícios",
    "companies.benefits.title": "O ROI de um bom espaço de trabalho",
    "companies.benefits.description": "Investir no ambiente de trabalho não é um custo, é uma estratégia de negócio. Espaços bem desenhados impactam diretamente a cultura, produtividade e retenção.",
    "companies.benefits.1": "Digitalização inteligente com BIM integrado",
    "companies.benefits.2": "Redução de riscos e otimização de recursos",
    "companies.benefits.3": "Análise preditiva e simulações paramétricas",
    "companies.benefits.4": "Controlo de qualidade em todas as fases",
    "companies.benefits.5": "Ativos de alto desempenho e sustentáveis",
    "companies.benefits.6": "Colaboração estratégica de longo prazo",
    "companies.cta2.title": "Vamos transformar o seu espaço?",
    "companies.cta2.description": "Agende uma visita às suas instalações. Analisamos o espaço e apresentamos soluções que se adaptam ao seu orçamento e objetivos.",
    "companies.cta2.button": "Agendar Visita",
    
    // Investors Page
    "investors.subtitle": "Investidores",
    "investors.title": "Maximize o",
    "investors.titleHighlight": "retorno",
    "investors.titleEnd": "do seu investimento",
    "investors.description": "Transformamos oportunidades imobiliárias em projetos rentáveis. Estudos de viabilidade rigorosos, licenciamento eficiente e execução de excelência.",
    "investors.cta": "Solicitar Estudo de Viabilidade",
    "investors.metrics.1.value": "€50M+",
    "investors.metrics.1.label": "Valor total de projetos",
    "investors.metrics.2.value": "25+",
    "investors.metrics.2.label": "Empreendimentos",
    "investors.metrics.3.value": "18%",
    "investors.metrics.3.label": "ROI médio",
    "investors.metrics.4.value": "100%",
    "investors.metrics.4.label": "Licenciamentos aprovados",
    "investors.services.subtitle": "Serviços",
    "investors.services.title": "Soluções para investidores",
    "investors.services.1.title": "Consultoria Estratégica e Viabilidade",
    "investors.services.1.description": "Análise técnica e financeira completa com simulações paramétricas para fundamentar decisões de investimento.",
    "investors.services.2.title": "Design Arquitetónico e Técnico",
    "investors.services.2.description": "Projetos integrados com modelação BIM, coordenação de especialidades e gestão de construção.",
    "investors.services.3.title": "Eficiência e Sustentabilidade",
    "investors.services.3.description": "Soluções inovadoras para reduzir riscos, otimizar recursos e garantir ativos de alto desempenho.",
    "investors.process.subtitle": "Metodologia",
    "investors.process.title": "Do terreno ao retorno",
    "investors.process.1.step": "01",
    "investors.process.1.title": "Análise de Oportunidade",
    "investors.process.1.description": "Avaliação do terreno ou edifício, zonamento urbanístico e potencial de valorização.",
    "investors.process.2.step": "02",
    "investors.process.2.title": "Estudo de Viabilidade",
    "investors.process.2.description": "Projeto conceptual com análise de custos, cronograma e projeção de rentabilidade.",
    "investors.process.3.step": "03",
    "investors.process.3.title": "Projeto e Licenciamento",
    "investors.process.3.description": "Desenvolvimento de projeto aprovado pelas entidades, com acompanhamento do processo.",
    "investors.process.4.step": "04",
    "investors.process.4.title": "Execução e Entrega",
    "investors.process.4.description": "Fiscalização da obra, controlo de qualidade e cumprimento de prazos.",
    "investors.caseStudy.subtitle": "Caso de Estudo",
    "investors.caseStudy.title": "Empreendimento Tejo View",
    "investors.caseStudy.description": "Reabilitação de edifício histórico em zona ARU (Área de Reabilitação Urbana) com 12 apartamentos de luxo e 2 espaços comerciais no rés-do-chão.",
    "investors.caseStudy.investment": "Investimento total",
    "investors.caseStudy.roi": "ROI em 24 meses",
    "investors.caseStudy.area": "Área bruta",
    "investors.caseStudy.timeline": "Prazo de construção",
    "investors.caseStudy.viewMore": "Ver mais casos de estudo",
    "investors.cta2.title": "Tem uma oportunidade de investimento?",
    "investors.cta2.description": "Solicite um estudo de viabilidade gratuito para o seu terreno ou edifício. Analisamos o potencial e apresentamos cenários de investimento.",
    "investors.cta2.button": "Solicitar Análise Gratuita",
    
    // Contact Page
    "contact.subtitle": "Contacto",
    "contact.title": "Vamos conversar sobre o seu projeto",
    "contact.description": "Tem um projeto em mente? Queremos conhecê-lo. A primeira consulta é gratuita e sem compromisso.",
    "contact.address": "Morada",
    "contact.phone": "Telefone / WhatsApp",
    "contact.email": "Email",
    "contact.hours": "Horário",
    "contact.weekdays": "Seg - Sex: 9h - 18h",
    "contact.saturday": "Sáb: Com marcação",
    "contact.whatToExpect": "O que esperar",
    "contact.response24h": "Resposta em até 24 horas",
    "contact.freeConsultation": "Consulta inicial gratuita",
    "contact.detailedProposal": "Proposta detalhada sem compromisso",
    "contact.fullName": "Nome completo",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Telefone",
    "contact.clientType": "Tipo de cliente",
    "contact.selectOption": "Selecione...",
    "contact.privateClient": "Cliente Privado",
    "contact.company": "Empresa",
    "contact.investor": "Investidor",
    "contact.service": "Serviço pretendido",
    "contact.consulting": "Consultoria Estratégica e Viabilidade",
    "contact.design": "Design Arquitetónico e Técnico",
    "contact.bim": "Modelação e Coordenação BIM",
    "contact.simulations": "Análise Preditiva e Simulações",
    "contact.construction": "Gestão de Construção",
    "contact.sustainability": "Eficiência e Sustentabilidade",
    "contact.other": "Outro",
    "contact.message": "Mensagem",
    "contact.messagePlaceholder": "Descreva brevemente o seu projeto...",
    "contact.send": "Enviar mensagem",
    "contact.sending": "A enviar...",
    "contact.successTitle": "Mensagem enviada!",
    "contact.successMessage": "Entraremos em contacto consigo em breve.",
    "contact.errorTitle": "Erro ao enviar",
    "contact.errorMessage": "Por favor tente novamente mais tarde.",
    "contact.namePlaceholder": "O seu nome",
    "contact.emailPlaceholder": "email@exemplo.pt",
    "contact.phonePlaceholder": "+351 900 000 000",
    "contact.mapPlaceholder": "Mapa — Avenida de Berna, 31, 1050-038 Lisboa",
    
    // Auth Page
    "auth.login": "Entrar",
    "auth.signup": "Criar conta",
    "auth.loginTitle": "Bem-vindo de volta",
    "auth.signupTitle": "Crie a sua conta",
    "auth.loginDescription": "Entre na sua área de cliente",
    "auth.signupDescription": "Registe-se para acompanhar os seus projetos",
    "auth.email": "Email",
    "auth.password": "Palavra-passe",
    "auth.fullName": "Nome completo",
    "auth.confirmPassword": "Confirmar palavra-passe",
    "auth.loginButton": "Entrar",
    "auth.signupButton": "Criar conta",
    "auth.loggingIn": "A entrar...",
    "auth.signingUp": "A criar conta...",
    "auth.noAccount": "Ainda não tem conta?",
    "auth.hasAccount": "Já tem conta?",
    "auth.createAccount": "Criar conta",
    "auth.loginHere": "Entre aqui",
    "auth.successTitle": "Conta criada!",
    "auth.successMessage": "Verifique o seu email para confirmar a conta.",
    "auth.errorTitle": "Erro",
    "auth.passwordMismatch": "As palavras-passe não coincidem",
    "auth.backToHome": "Voltar ao início",
    
    // WhatsApp
    "whatsapp.tooltip": "Fale connosco no WhatsApp",
    "whatsapp.message": "Olá, gostaria de mais informações sobre os vossos serviços.",
    
    // Common
    "common.required": "obrigatório",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.private": "Private",
    "nav.companies": "Companies",
    "nav.investors": "Investors",
    "nav.portfolio": "Portfolio",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.quote": "Get Quote",
    "nav.login": "Login",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "nav.clientArea": "Client Area",
    "nav.logout": "Logout",
    "nav.theme": "Theme",
    "nav.language": "Language",
    
    // Hero Section
    "hero.tagline": "Architecture & Design",
    "hero.title": "We create spaces that",
    "hero.titleHighlight": "inspire",
    "hero.description": "We design future-ready ecosystems — for living, working and learning. We combine 20+ years of international experience with digital innovation and sustainability.",
    "hero.cta": "Get Quote",
    "hero.viewPortfolio": "View Portfolio",
    "hero.experience": "Years of international experience in architecture",
    "hero.imageAlt": "ARIFA Studio architecture project",
    
    // About Section
    "about.subtitle": "About Us",
    "about.title": "Architecture with Portuguese soul,",
    "about.titleHighlight": "global vision",
    "about.description1": "ARIFA Studio combines over 20 years of international experience in architecture, with projects developed in Portugal, Norway, Sweden and Angola. Founded in 2022, we bring a contemporary vision focused on the digital transformation of the construction sector.",
    "about.description2": "We specialize in BIM, sustainable design, energy efficiency and innovative solutions. We believe in intelligent digitalization, strategic collaboration and ethical and sustainable practices to create high-performance assets.",
    "about.quote": "Design is intelligence made visible",
    "about.stat1": "Years of experience",
    "about.stat2": "Countries of operation",
    "about.stat3": "Digital specialization",
    "about.stat4": "Studio foundation",
    "about.explorePortfolio": "Explore Portfolio",
    
    // CTA Section
    "cta.subtitle": "Start today",
    "cta.title": "Ready to bring your project to life?",
    "cta.description": "Whether it's a dream home, an innovative corporate space or a strategic real estate investment — we're here to turn your vision into reality.",
    "cta.freeConsultation": "Free consultation",
    "cta.freeConsultationDesc": "First meeting without obligation to understand your project",
    "cta.response24h": "24h response",
    "cta.response24hDesc": "We guarantee a quick response to all requests",
    "cta.detailedQuote": "Detailed quote",
    "cta.detailedQuoteDesc": "Clear and transparent proposal with no surprises",
    "cta.requestQuote": "Request Quote",
    "cta.imageAlt": "Meeting with ARIFA Studio team",
    
    // Segment Selector
    "segments.subtitle": "How we can help",
    "segments.title": "Solutions tailored to your needs",
    "segments.description": "Every client is unique. That's why we offer specialized services for different profiles and objectives.",
    "segments.learnMore": "Learn more",
    "segments.private.title": "Private Clients",
    "segments.private.description": "We transform your vision into a dream home. From villas to apartments, we create spaces that reflect your personality.",
    "segments.private.feature1": "Single-family homes",
    "segments.private.feature2": "Renovations",
    "segments.private.feature3": "Interior design",
    "segments.companies.title": "Companies",
    "segments.companies.description": "Corporate spaces that boost productivity and well-being. Solutions for offices, retail and hospitality.",
    "segments.companies.feature1": "Offices",
    "segments.companies.feature2": "Commercial spaces",
    "segments.companies.feature3": "Hotels and restaurants",
    "segments.investors.title": "Investors",
    "segments.investors.description": "We maximize the return on your real estate investment. Feasibility studies, development projects and urban rehabilitation.",
    "segments.investors.feature1": "Feasibility studies",
    "segments.investors.feature2": "Real estate development",
    "segments.investors.feature3": "Urban rehabilitation",
    
    // Featured Projects
    "projects.subtitle": "Portfolio",
    "projects.title": "Featured projects",
    "projects.viewAll": "View all projects",
    
    // Testimonials
    "testimonials.subtitle": "Testimonials",
    "testimonials.title": "What our clients say",
    "testimonials.previous": "Previous",
    "testimonials.next": "Next",
    "testimonials.goTo": "Go to testimonial",
    
    // Footer
    "footer.tagline": "We design future-ready ecosystems for living, working and learning.",
    "footer.segments": "Segments",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.contact": "Contact",
    "footer.newsletter": "Newsletter",
    "footer.newsletterDesc": "Receive news and architecture tips.",
    "footer.copyright": "All rights reserved.",
    "footer.aboutUs": "About Us",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.terms": "Terms and Conditions",
    
    // Portfolio Page
    "portfolio.subtitle": "Portfolio",
    "portfolio.title": "Our projects",
    "portfolio.description": "A selection of our most recent work in architecture, interior design and real estate development.",
    "portfolio.searchPlaceholder": "Search projects...",
    "portfolio.allSegments": "All Segments",
    "portfolio.all": "All",
    "portfolio.allLocations": "All",
    "portfolio.noResults": "No projects found with the selected filters.",
    "portfolio.noProjects": "No projects found.",
    "portfolio.clearFilters": "Clear filters",
    "portfolio.projectsFound": "projects found",
    "portfolio.projectFound": "project found",
    "portfolio.cta.title": "Have a project in mind?",
    "portfolio.cta.description": "Tell us about your ideas. We're ready to turn your vision into reality.",
    "portfolio.cta.button": "Contact Us",
    
    // Private Page
    "private.subtitle": "Private Clients",
    "private.title": "The home of your",
    "private.titleHighlight": "dreams",
    "private.description": "We create spaces that tell your story. Each project is unique, developed according to your needs, lifestyle and aspirations.",
    "private.cta": "Book Free Consultation",
    "private.services.subtitle": "Services",
    "private.services.title": "Solutions for your home",
    "private.services.1.title": "Single-Family Homes",
    "private.services.1.description": "Custom projects from scratch that combine functionality, aesthetics and sustainability. From concept to turnkey delivery.",
    "private.services.2.title": "Interior Design",
    "private.services.2.description": "Spaces that reflect your personality. Selection of materials, furniture and lighting to create unique environments.",
    "private.services.3.title": "Renovations",
    "private.services.3.description": "We transform existing spaces into modern and functional homes, respecting the building's original identity.",
    "private.process.subtitle": "Process",
    "private.process.title": "How we work with you",
    "private.process.1.title": "Initial Consultation",
    "private.process.1.description": "Meeting to understand your needs, tastes and budget.",
    "private.process.2.title": "Preliminary Study",
    "private.process.2.description": "Presentation of concepts and spatial solutions for approval.",
    "private.process.3.title": "Execution Project",
    "private.process.3.description": "Detailed development of all technical elements.",
    "private.process.4.title": "Construction Supervision",
    "private.process.4.description": "Construction supervision to ensure quality and compliance.",
    "private.cta2.title": "Ready to start?",
    "private.cta2.description": "The first consultation is free and without obligation. Tell us about your project and let's turn it into reality.",
    "private.cta2.button": "Schedule Consultation",
    
    // Companies Page
    "companies.subtitle": "Companies",
    "companies.title": "Spaces that",
    "companies.titleHighlight": "transform",
    "companies.titleEnd": "businesses",
    "companies.description": "The work environment directly influences your team's performance. We create corporate spaces that inspire, motivate and retain talent.",
    "companies.cta": "Request Proposal",
    "companies.services.subtitle": "Areas of Expertise",
    "companies.services.title": "Solutions for companies",
    "companies.services.1.title": "Offices & Workspaces",
    "companies.services.1.description": "People-centered design with BIM integration. Spaces that boost productivity, well-being and talent retention.",
    "companies.services.2.title": "Educational & Healthcare Facilities",
    "companies.services.2.description": "Schools, training centers and healthcare facilities designed for high performance and user comfort.",
    "companies.services.3.title": "Senior Living & Hospitality",
    "companies.services.3.description": "Assisted living spaces and hospitality focused on accessibility, sustainability and user experience.",
    "companies.benefits.subtitle": "Benefits",
    "companies.benefits.title": "The ROI of a good workspace",
    "companies.benefits.description": "Investing in the work environment is not a cost, it's a business strategy. Well-designed spaces directly impact culture, productivity and retention.",
    "companies.benefits.1": "Intelligent digitalization with integrated BIM",
    "companies.benefits.2": "Risk reduction and resource optimization",
    "companies.benefits.3": "Predictive analysis and parametric simulations",
    "companies.benefits.4": "Quality control at all stages",
    "companies.benefits.5": "High-performance and sustainable assets",
    "companies.benefits.6": "Long-term strategic collaboration",
    "companies.cta2.title": "Ready to transform your space?",
    "companies.cta2.description": "Schedule a visit to your facilities. We analyze the space and present solutions that fit your budget and objectives.",
    "companies.cta2.button": "Schedule Visit",
    
    // Investors Page
    "investors.subtitle": "Investors",
    "investors.title": "Maximize the",
    "investors.titleHighlight": "return",
    "investors.titleEnd": "on your investment",
    "investors.description": "We transform real estate opportunities into profitable projects. Rigorous feasibility studies, efficient licensing and excellent execution.",
    "investors.cta": "Request Feasibility Study",
    "investors.metrics.1.value": "€50M+",
    "investors.metrics.1.label": "Total project value",
    "investors.metrics.2.value": "25+",
    "investors.metrics.2.label": "Developments",
    "investors.metrics.3.value": "18%",
    "investors.metrics.3.label": "Average ROI",
    "investors.metrics.4.value": "100%",
    "investors.metrics.4.label": "Licenses approved",
    "investors.services.subtitle": "Services",
    "investors.services.title": "Solutions for investors",
    "investors.services.1.title": "Strategic Consulting and Feasibility",
    "investors.services.1.description": "Complete technical and financial analysis with parametric simulations to support investment decisions.",
    "investors.services.2.title": "Architectural and Technical Design",
    "investors.services.2.description": "Integrated projects with BIM modeling, specialty coordination and construction management.",
    "investors.services.3.title": "Efficiency and Sustainability",
    "investors.services.3.description": "Innovative solutions to reduce risks, optimize resources and ensure high-performance assets.",
    "investors.process.subtitle": "Methodology",
    "investors.process.title": "From land to return",
    "investors.process.1.step": "01",
    "investors.process.1.title": "Opportunity Analysis",
    "investors.process.1.description": "Evaluation of the land or building, urban zoning and appreciation potential.",
    "investors.process.2.step": "02",
    "investors.process.2.title": "Feasibility Study",
    "investors.process.2.description": "Conceptual project with cost analysis, timeline and profitability projection.",
    "investors.process.3.step": "03",
    "investors.process.3.title": "Design and Licensing",
    "investors.process.3.description": "Development of an approved project by the authorities, with process monitoring.",
    "investors.process.4.step": "04",
    "investors.process.4.title": "Execution and Delivery",
    "investors.process.4.description": "Construction supervision, quality control and deadline compliance.",
    "investors.caseStudy.subtitle": "Case Study",
    "investors.caseStudy.title": "Tejo View Development",
    "investors.caseStudy.description": "Rehabilitation of a historic building in an ARU (Urban Rehabilitation Area) zone with 12 luxury apartments and 2 commercial spaces on the ground floor.",
    "investors.caseStudy.investment": "Total investment",
    "investors.caseStudy.roi": "ROI in 24 months",
    "investors.caseStudy.area": "Gross area",
    "investors.caseStudy.timeline": "Construction time",
    "investors.caseStudy.viewMore": "View more case studies",
    "investors.cta2.title": "Have an investment opportunity?",
    "investors.cta2.description": "Request a free feasibility study for your land or building. We analyze the potential and present investment scenarios.",
    "investors.cta2.button": "Request Free Analysis",
    
    // Contact Page
    "contact.subtitle": "Contact",
    "contact.title": "Let's talk about your project",
    "contact.description": "Have a project in mind? We want to know about it. The first consultation is free and without obligation.",
    "contact.address": "Address",
    "contact.phone": "Phone / WhatsApp",
    "contact.email": "Email",
    "contact.hours": "Hours",
    "contact.weekdays": "Mon - Fri: 9am - 6pm",
    "contact.saturday": "Sat: By appointment",
    "contact.whatToExpect": "What to expect",
    "contact.response24h": "Response within 24 hours",
    "contact.freeConsultation": "Free initial consultation",
    "contact.detailedProposal": "Detailed proposal without obligation",
    "contact.fullName": "Full name",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Phone",
    "contact.clientType": "Client type",
    "contact.selectOption": "Select...",
    "contact.privateClient": "Private Client",
    "contact.company": "Company",
    "contact.investor": "Investor",
    "contact.service": "Desired service",
    "contact.consulting": "Strategic Consulting and Feasibility",
    "contact.design": "Architectural and Technical Design",
    "contact.bim": "BIM Modeling and Coordination",
    "contact.simulations": "Predictive Analysis and Simulations",
    "contact.construction": "Construction Management",
    "contact.sustainability": "Efficiency and Sustainability",
    "contact.other": "Other",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Briefly describe your project...",
    "contact.send": "Send message",
    "contact.sending": "Sending...",
    "contact.successTitle": "Message sent!",
    "contact.successMessage": "We will contact you soon.",
    "contact.errorTitle": "Error sending",
    "contact.errorMessage": "Please try again later.",
    "contact.namePlaceholder": "Your name",
    "contact.emailPlaceholder": "email@example.com",
    "contact.phonePlaceholder": "+351 900 000 000",
    "contact.mapPlaceholder": "Map — Avenida de Berna, 31, 1050-038 Lisbon",
    
    // Auth Page
    "auth.login": "Login",
    "auth.signup": "Sign up",
    "auth.loginTitle": "Welcome back",
    "auth.signupTitle": "Create your account",
    "auth.loginDescription": "Access your client area",
    "auth.signupDescription": "Register to track your projects",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullName": "Full name",
    "auth.confirmPassword": "Confirm password",
    "auth.loginButton": "Login",
    "auth.signupButton": "Create account",
    "auth.loggingIn": "Logging in...",
    "auth.signingUp": "Creating account...",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.createAccount": "Create account",
    "auth.loginHere": "Login here",
    "auth.successTitle": "Account created!",
    "auth.successMessage": "Check your email to confirm your account.",
    "auth.errorTitle": "Error",
    "auth.passwordMismatch": "Passwords don't match",
    "auth.backToHome": "Back to home",
    
    // WhatsApp
    "whatsapp.tooltip": "Chat with us on WhatsApp",
    "whatsapp.message": "Hello, I would like more information about your services.",
    
    // Common
    "common.required": "required",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("arifa-language");
    return (saved as Language) || "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("arifa-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.pt] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
